# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# pre-commit==2.13.0
default_install_hook_types: [pre-commit, prepare-commit-msg]
ci:
  autofix_commit_msg: ":rotating_light: auto fix by pre-commit hooks"
  autofix_prs: true
  autoupdate_branch: main
  autoupdate_schedule: weekly
  autoupdate_commit_msg: ":arrow_up: auto update by pre-commit hooks"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  #  - repo: https://github.com/PyCQA/flake8
  #    rev: 3.9.2
  #    hooks:
  #      - id: flake8

  #  - repo: https://github.com/psf/black
  #    rev: 21.6b0
  #    hooks:
  #      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, markdown, yaml, json]
        stages: [commit]
#  - repo: https://github.com/sourcery-ai/sourcery
#    rev: v1.0.4
#    hooks:
#      - id: sourcery
# The best way to use Sourcery in a pre-commit hook:
# * review only changed lines:
# * omit the summary
#        args: [--diff=git diff HEAD, --no-summary]

#exclude: |
#  (?x)^(
#    etc|
#    .*?/migrations|
#    bmiss/settings/instance.*|
#    .*?proto.*
#  )
