FROM python:3.9

LABEL maintainer="HsiangNianian <i@jyunko.cn>"
LABEL org.opencontainers.image.description="A simple iamai examples with python 3.10"

WORKDIR /app

ADD /examples /app/

RUN pip install iamai[all]

CMD ["pdm", "run", "main.py"]