[tool.poetry]
name = "iamai"
version = "3.14"
description = "bot framework."
authors = ["简律纯 <admin@jyunko.cn>"]
license = "MIT"
readme = "README.md"
homepage = "https://retrofor.space/"
repository = "https://github.com/retrofor/iamai"
documentation = "https://iamai.retrofor.space/"
keywords = ["bot", "qq", "qqbot", "mirai", "coolq"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Framework :: Robot Framework",
  "Framework :: Robot Framework :: Library",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3"
]
packages = [
  { include = "iamai" },
]
include = ["iamai/py.typed"]

[tool.poetry.dependencies]
python = "^3.8"
tomli = "^2.0.1"
flask = "^2.2.2"
loguru = "^0.6.0"
aiohttp = "^3.8.4"
typing-extensions = "^4.5.0"
pydantic = "^1.10.4"
watchfiles = "^0.18.1"
apscheduler = "^3.10.0"
onedice = "^1.0.5"

fastapi = { version = ">=0.87.0,!=0.89.0,<1.0.0", optional = true }

[tool.poetry.group.dev.dependencies]
pycln = "^2.1.2"
isort = "^5.10.1"
black = "^23.1.0"
nonemoji = "^0.1.2"
pre-commit = "^3.0.0"

[tool.poetry.group.test.dependencies]
pytest-cov = "^4.0.0"
pytest-xdist = "^3.2.0"
pytest-asyncio = "^0.20.0"

[tool.poetry.extras]
httpx = ["httpx"]
aiohttp = ["aiohttp"]
websockets = ["websockets"]
quart = ["quart", "uvicorn"]
fastapi = ["fastapi", "uvicorn"]
all = ["fastapi", "quart", "aiohttp", "httpx", "websockets", "uvicorn"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "--cov=iamai --cov-report=term-missing"
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
]

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311"]
include = '\.pyi?$'
extend-exclude = '''
'''

[tool.isort]
profile = "black"
line_length = 88
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
src_paths = ["iamai", "test"]
extra_standard_library = ["typing_extensions"]

[tool.pycln]
path = "."
all = false

[tool.pyright]
reportShadowedImports = false
pythonVersion = "3.8"
pythonPlatform = "All"
executionEnvironments = [
  { root = "./test", extraPaths = ["./"] },
  { root = "./" },
]


[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
