[tool.poetry]
name = "iamai"
version = "3.2.4"
description = "bot framework."
authors = ["简律纯 <i@jyunko.cn>"]
license = "MIT"
readme = "README.md"
homepage = "https://retrofor.space/"
repository = "https://github.com/retrofor/iamai"
documentation = "https://iamai.retrofor.space/"
keywords = [
  "bot",
  "qq",
  "qqbot",
  "mirai",
  "coolq",
  "kook",
  "go-cqhttp",
  "dingtalk",
  "console",
  "apscheduler",
  "bilibili",
  "bilibili-live",
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Framework :: Robot Framework",
  "Framework :: Robot Framework :: Library",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
]

[tool.poetry.dependencies]
python = "^3.8"
tomli = { version = "^2.0.0", python = "<3.11" }
pydantic = ">=1.10,<3.0"
aiohttp = "^3.8.0"
loguru = ">=0.6,<0.8"
pyyaml = "^6.0"
typing-extensions = ">=4.7.0"

[tool.poetry.group.dev.dependencies]
watchfiles = "^0.18.0"
sophia-doc = "^0.1.0"
iamai-adapter-bililive = { path = "./packages/iamai-adapter-bililive", develop = true }
iamai-adapter-console = { path = "./packages/iamai-adapter-console", develop = true }
iamai-adapter-kook = { path = "./packages/iamai-adapter-kook", develop = true }
iamai-adapter-cqhttp = { path = "./packages/iamai-adapter-cqhttp", develop = true }
iamai-adapter-dingtalk = { path = "./packages/iamai-adapter-dingtalk", develop = true }
iamai-adapter-apscheduler = { path = "./packages/iamai-adapter-apscheduler", develop = true }
black = "^23.1.0"
isort = "^5.12.0"
pre-commit = "^3.1.0"
pre-commit-hooks = "^4.4.0"

[tool.poetry.extras]
kook = ["iamai-adapter-kook"]
mirai = ["iamai-adapter-mirai"]
cqhttp = ["iamai-adapter-cqhttp"]
console = ["iamai-adapter-console"]
bililive = ["iamai-adapter-bililive"]
dingtalk = ["iamai-adapter-dingtalk"]
apscheduler = ["iamai-adapter-apscheduler"]
hot_reload = ["watchfiles"]
all = [
  "iamai-adapter-mirai",
  "iamai-adapter-bililive",
  "iamai-adapter-console",
  "iamai-adapter-kook",
  "iamai-adapter-cqhttp",
  "iamai-adapter-dingtalk",
  "iamai-adapter-apscheduler",
  "watchfiles",
]

[tool.black]
target-version = ["py38", "py39", "py310", "py311"]

[tool.isort]
profile = "black"
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
src_paths = ["iamai", "tests"]
extra_standard_library = ["typing_extensions"]

[tool.pyright]
exclude = ["tests"]
pythonVersion = "3.8"
pythonPlatform = "All"
typeCheckingMode = "strict"
reportImportCycles = false
reportIncompatibleMethodOverride = false
reportMissingTypeArgument = false
reportMissingTypeStubs = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false
reportUnnecessaryIsInstance = false

[tool.pydantic-pycharm-plugin]
ignore-init-method-arguments = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
