[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "iamai"
dynamic = ["version"]
description = "Comprehensive AI Toolkit for Multimodal Learning and Cross-Platform Robotics."
authors = [{ name = "HsiangNianian", email = "i@jyunko.cn" }]
license = { text = "MIT" }
readme.content-type = "text/x-rst"
readme.text = """See the `documentation <https://iamai.is-a.dev/>`_."""
# readme = "README.rst"
keywords = [
    "bot",
    "red",
    "kook",
    "onebot11",
    "gensokyo",
    "dingtalk",
    "console",
    "apscheduler",
    "bilibili",
    "bilibili-live",
    "rust",
    "pyo3",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
    "Framework :: Robot Framework",
    "Framework :: Robot Framework :: Library",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Communications :: Chat",
]
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.0.3,<3.0.0",
    "aiohttp>=3.9.1",
    "loguru>=0.7.0,<0.8.0",
    "typing-extensions>=4.8.0",
    "requests>=2.31.0",
    "rich>=13.7.1",
    "click>=8.1.7",
    "polib>=1.2.0",
]

[project.optional-dependencies]
cqhttp = ["iamai-adapter-cqhttp"]
bililive = ["iamai-adapter-bililive"]
dingtalk = ["iamai-adapter-dingtalk"]
apscheduler = ["iamai-adapter-apscheduler"]
red = ["iamai-adapter-red"]
console = ["iamai-adapter-console"]
kook = ["iamai-adapter-kook"]
gensokyo = ["iamai-adapter-gensokyo"]
hot_reload = ["watchfiles"]
all = [
    "iamai-adapter-bililive",
    "iamai-adapter-cqhttp",
    "iamai-adapter-dingtalk",
    "iamai-adapter-apscheduler",
    "iamai-adapter-gensokyo",
    "iamai-adapter-console",
    "iamai-adapter-red",
    "iamai-adapter-kook",
    "watchfiles",
]

[project.urls]
Homepage = "https://iamai.is-a.dev"
Documentation = "https://iamai.is-a.dev"
Repository = "https://github.com/retrofor/iamai"
Changelog = "https://iamai.is-a.dev/en/latest/changelog.html#"

[project.scripts]
iamai = "iamai.__main__:main"

[tool.black]
target-version = ["py39", "py310", "py311"]

[tool.pdm.dev-dependencies]
dev = [
    "pip>=24.2",
    "maturin>=1.7.0",
    "typing>=3.7.4.3",
]
lint = [
    "ruff>=0.3.0",
    "mypy>=1.8.0",
    "pylint>=3.1.0",
    "pylint-pydantic>=0.3.2",
]
docs = [
    "tomlkit>=0.13.0",
    "sphinx>=7.1.2",
    "furo>=2024.1.29",
    "sphinx-autobuild>=2021.3.14",
    "myst-parser>=2.0.0",
    "tomli>=2.0.1",
    "sphinx-design>=0.5.0",
    "sphinx-intl>=2.1.0",
    "lint>=1.2.1",
    "black>=24.2.0",
    "ruff>=0.3.0",
    "pylint>=3.1.0",
    "pylint-pydantic>=0.3.2",
    "sphinx-last-updated-by-git>=0.3.8",
]
test = [
    "pytest>=8.0.2",
    "pytest-asyncio>=0.23.5",
    "pytest-xdist>=3.5.0",
    "pytest-cov>=4.1.0",
]
typing = ["watchfiles>=0.21.0", "trio>=0.24.0"]
# adapters = [
#     "-e iamai-adapter-cqhttp @ file:///${PROJECT_ROOT}/packages/iamai-adapter-cqhttp",
#     "-e iamai-adapter-bililive @ file:///${PROJECT_ROOT}/packages/iamai-adapter-bililive",
#     "-e iamai-adapter-console @ file:///${PROJECT_ROOT}/packages/iamai-adapter-console",
#     "-e iamai-adapter-dingtalk @ file:///${PROJECT_ROOT}/packages/iamai-adapter-dingtalk",
#     "-e iamai-adapter-red @ file:///${PROJECT_ROOT}/packages/iamai-adapter-red",
#     "-e iamai-adapter-apscheduler @ file:///${PROJECT_ROOT}/packages/iamai-adapter-apscheduler",
#     "-e iamai-adapter-gensokyo @ file:///${PROJECT_ROOT}/packages/iamai-adapter-gensokyo",
#     "-e iamai-adapter-kook @ file:///${PROJECT_ROOT}/packages/iamai-adapter-kook",
# ]
adapters = [
    "iamai-adapter-cqhttp @ file:///${PROJECT_ROOT}/packages/iamai-adapter-cqhttp",
]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "iamai.libcore"
# include = [{ path = "iamai/**/*", format = "sdist" }, "README.rst"]

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.10
target-version = "py39"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E4", "E7", "E9", "F"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"