d = \
{
  "action": "published",
  "release": {
    "url": "https://api.github.com/repos/retrofor/iamai/releases/93160331",
    "assets_url": "https://api.github.com/repos/retrofor/iamai/releases/93160331/assets",
    "upload_url": "https://uploads.github.com/repos/retrofor/iamai/releases/93160331/assets{?name,label}",
    "html_url": "https://github.com/retrofor/iamai/releases/tag/v3.14",
    "id": 93160331,
    "author": {
      "login": "github-actions[bot]",
      "id": 41898282,
      "node_id": "MDM6Qm90NDE4OTgyODI=",
      "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/github-actions%5Bbot%5D",
      "html_url": "https://github.com/apps/github-actions",
      "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
      "type": "Bot",
      "site_admin": 1
    },
    "node_id": "RE_kwDOI0dmkM4FjYOL",
    "tag_name": "v3.14",
    "target_commitish": "refs/heads/main",
    "name": "v3.14 🌈",
    "draft": 1,
    "prerelease": 1,
    "created_at": "2023-02-28T18:04:42Z",
    "published_at": "2023-02-28T18:07:51Z",
    "assets": [

    ],
    "tarball_url": "https://api.github.com/repos/retrofor/iamai/tarball/v3.14",
    "zipball_url": "https://api.github.com/repos/retrofor/iamai/zipball/v3.14",
    "body": "## Changes\r\n- merge into #104 @HsiangNianian (#105)\r\n- :arrow\\_up: auto update by pre-commit hooks @pre-commit-ci (#98)\r\n\r\n## 🚀 Features\r\n\r\n-  🐱‍🏍OHHH!!!!!支持了自身群聊私聊消息的接收 @HsiangNianian (#106)\r\n- ✨config内的`adapter.cqhttp`添加了`debug(true/false)`键 @HsiangNianian (#104)\r\n\r\n## 🔝 Dependencies\r\n\r\n- Update pypa/gh-action-pypi-publish requirement to master @dependabot (#111)\r\n- Bump typing-extensions from 4.4.0 to 4.5.0 @dependabot (#100)\r\n- Bump werkzeug from 2.2.2 to 2.2.3 @dependabot (#103)\r\n- Bump aiohttp from 3.8.3 to 3.8.4 @dependabot (#96)\r\n- Bump fastapi from 0.90.1 to 0.91.0 @dependabot (#95)\r\n",
    "mentions_count": 3
  },
  "repository": {
    "id": 591881872,
    "node_id": "R_kgDOI0dmkA",
    "name": "iamai",
    "full_name": "retrofor/iamai",
    "private": 1,
    "owner": {
      "login": "retrofor",
      "id": 119327113,
      "node_id": "O_kgDOBxzJiQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/119327113?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/retrofor",
      "html_url": "https://github.com/retrofor",
      "followers_url": "https://api.github.com/users/retrofor/followers",
      "following_url": "https://api.github.com/users/retrofor/following{/other_user}",
      "gists_url": "https://api.github.com/users/retrofor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/retrofor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/retrofor/subscriptions",
      "organizations_url": "https://api.github.com/users/retrofor/orgs",
      "repos_url": "https://api.github.com/users/retrofor/repos",
      "events_url": "https://api.github.com/users/retrofor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/retrofor/received_events",
      "type": "Organization",
      "site_admin": 1
    },
    "html_url": "https://github.com/retrofor/iamai",
    "description": "Cross-platform robot framework, mainly used for machine learning | 跨平台机器人框架+深度学习框架",
    "fork": 1,
    "url": "https://api.github.com/repos/retrofor/iamai",
    "forks_url": "https://api.github.com/repos/retrofor/iamai/forks",
    "keys_url": "https://api.github.com/repos/retrofor/iamai/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/retrofor/iamai/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/retrofor/iamai/teams",
    "hooks_url": "https://api.github.com/repos/retrofor/iamai/hooks",
    "issue_events_url": "https://api.github.com/repos/retrofor/iamai/issues/events{/number}",
    "events_url": "https://api.github.com/repos/retrofor/iamai/events",
    "assignees_url": "https://api.github.com/repos/retrofor/iamai/assignees{/user}",
    "branches_url": "https://api.github.com/repos/retrofor/iamai/branches{/branch}",
    "tags_url": "https://api.github.com/repos/retrofor/iamai/tags",
    "blobs_url": "https://api.github.com/repos/retrofor/iamai/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/retrofor/iamai/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/retrofor/iamai/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/retrofor/iamai/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/retrofor/iamai/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/retrofor/iamai/languages",
    "stargazers_url": "https://api.github.com/repos/retrofor/iamai/stargazers",
    "contributors_url": "https://api.github.com/repos/retrofor/iamai/contributors",
    "subscribers_url": "https://api.github.com/repos/retrofor/iamai/subscribers",
    "subscription_url": "https://api.github.com/repos/retrofor/iamai/subscription",
    "commits_url": "https://api.github.com/repos/retrofor/iamai/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/retrofor/iamai/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/retrofor/iamai/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/retrofor/iamai/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/retrofor/iamai/contents/{+path}",
    "compare_url": "https://api.github.com/repos/retrofor/iamai/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/retrofor/iamai/merges",
    "archive_url": "https://api.github.com/repos/retrofor/iamai/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/retrofor/iamai/downloads",
    "issues_url": "https://api.github.com/repos/retrofor/iamai/issues{/number}",
    "pulls_url": "https://api.github.com/repos/retrofor/iamai/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/retrofor/iamai/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/retrofor/iamai/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/retrofor/iamai/labels{/name}",
    "releases_url": "https://api.github.com/repos/retrofor/iamai/releases{/id}",
    "deployments_url": "https://api.github.com/repos/retrofor/iamai/deployments",
    "created_at": "2023-01-22T07:42:56Z",
    "updated_at": "2023-02-28T16:48:31Z",
    "pushed_at": "2023-02-28T18:07:50Z",
    "git_url": "git://github.com/retrofor/iamai.git",
    "ssh_url": "git@github.com:retrofor/iamai.git",
    "clone_url": "https://github.com/retrofor/iamai.git",
    "svn_url": "https://github.com/retrofor/iamai",
    "homepage": "https://iamai.retrofor.space",
    "size": 42396,
    "stargazers_count": 6,
    "watchers_count": 6,
    "language": "Python",
    "has_issues": 1,
    "has_projects": 1,
    "has_downloads": 1,
    "has_wiki": 1,
    "has_pages": 1,
    "has_discussions": 1,
    "forks_count": 3,
    "mirror_url": 1,
    "archived": 1,
    "disabled": 1,
    "open_issues_count": 18,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": 1,
    "is_template": 1,
    "web_commit_signoff_required": 1,
    "topics": [
      "ai",
      "artificial-intelligence",
      "bot",
      "gpt",
      "machine-learning",
      "ml",
      "onebot",
      "python",
      "rasa",
      "whl"
    ],
    "visibility": "public",
    "forks": 3,
    "open_issues": 18,
    "watchers": 6,
    "default_branch": "main"
  },
  "organization": {
    "login": "retrofor",
    "id": 119327113,
    "node_id": "O_kgDOBxzJiQ",
    "url": "https://api.github.com/orgs/retrofor",
    "repos_url": "https://api.github.com/orgs/retrofor/repos",
    "events_url": "https://api.github.com/orgs/retrofor/events",
    "hooks_url": "https://api.github.com/orgs/retrofor/hooks",
    "issues_url": "https://api.github.com/orgs/retrofor/issues",
    "members_url": "https://api.github.com/orgs/retrofor/members{/member}",
    "public_members_url": "https://api.github.com/orgs/retrofor/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/119327113?v=4",
    "description": "<script>alert('大家抱怨的和没人用的')</script>"
  },
  "sender": {
    "login": "HsiangNianian",
    "id": 44714368,
    "node_id": "MDQ6VXNlcjQ0NzE0MzY4",
    "avatar_url": "https://avatars.githubusercontent.com/u/44714368?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/HsiangNianian",
    "html_url": "https://github.com/HsiangNianian",
    "followers_url": "https://api.github.com/users/HsiangNianian/followers",
    "following_url": "https://api.github.com/users/HsiangNianian/following{/other_user}",
    "gists_url": "https://api.github.com/users/HsiangNianian/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/HsiangNianian/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/HsiangNianian/subscriptions",
    "organizations_url": "https://api.github.com/users/HsiangNianian/orgs",
    "repos_url": "https://api.github.com/users/HsiangNianian/repos",
    "events_url": "https://api.github.com/users/HsiangNianian/events{/privacy}",
    "received_events_url": "https://api.github.com/users/HsiangNianian/received_events",
    "type": "User",
    "site_admin": False
  }
}

print("{release[author][login]} {action} {release[tag_name]} in \"{repository[full_name]}\"\n{release[name]}\n{release[body]}".format(**d))