# 基础示例配置文件

[bot]
bot_name = "iamai"
plugins = []
plugin_dir = ["plugins"]
middlewares = ["iamai.middleware.console"]
hot_reload = false
debug = false

[bot.log]
level = "INFO"
log_file = "iamai.log"
console = true

[middleware.console]
middleware_connect_type = "direct"
bot_name = "iamai"
bot_id = "iamai_bot"
user_name = "User"
user_id = "user_001"
