backend:
  name: github
  repo: retrofor/IamAI # Path to your GitHub repository
  # optional, defaults to master
  branch: main
  #   use_graphql: true
  squash_merges: true
  commit_messages:
    create: ✨{{author-login}} Create {{collection}} “{{slug}}”
    update: 🐱‍🏍{{author-login}} Update {{collection}} “{{slug}}”
    delete: 🐱‍👤{{author-login}} Delete {{collection}} “{{slug}}”
    uploadMedia: ✨{{author-login}} Upload “{{path}}”
    deleteMedia: 🐱‍{{author-login}} Delete “{{path}}”
    openAuthoring: "{{author-login}}: {{message}}"
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
publish_mode: editorial_workflow
media_folder: "/website/static/img/post" # 存放图片的文件夹
public_folder: "/website/img/post" # 上传图片的src属性会以该路径开头
logo_url: https://IamAI.retrofor.space/img/logo.png

# i18n:
#   # Required and can be one of multiple_folders, multiple_files or single_file
#   # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
#   # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
#   # single_file - persists a single file in `<folder>/<slug>.<extension>`
#   structure: multiple_folders

#   # Required - a list of locales to show in the editor UI
#   locales: [en, zh]

#   # Optional, defaults to the first item in locales.
#   # The locale to be used for fields validation and as a baseline for the entry.
#   default_locale: en

collections:
  - name: "opt" # 定义该collection的路径
    label: "blog" # 后台显示的名字
    folder: "website/blog"
    create: true # 允许创建新文件
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: "{{title}}" # optional summary for a tree node, defaults to the inferred title field
    slug: "{{slug}}" # 文件名字模版，{{slug}} 取自title
    fields: # 定义front matter的显示与数据类型
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Authors",
          name: "authors",
          widget: "string",
          default: "Hsiang_Nianian",
        }
      - { label: "Type", name: "type", widget: "string", default: "post" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Series", name: "series", widget: "list", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Lastmod",
          name: "lastmod",
          widget: "date",
          default: "",
          required: false,
          format: "YYYY-MM-DD",
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - {
          label: "Featured Image",
          name: "featured",
          widget: "image",
          required: false,
        }
      - {
          label: "Featured Alt",
          name: "featuredalt",
          widget: "string",
          required: false,
        }
      - {
          label: "Featured Path",
          name: "featuredpath",
          widget: "string",
          default: "img/post",
          required: false,
        }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: false,
          required: false,
        }
      - {
          label: "Show TOC",
          name: "showtoc",
          widget: "boolean",
          default: true,
          required: false,
        }
      - { label: "Post Content", name: "body", widget: "markdown" }
  - name: "opt-2" # 定义该collection的路径
    label: "docs" # 后台显示的名字
    folder: "website/docs"
    create: true # 允许创建新文件
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: "{{title}}" # optional summary for a tree node, defaults to the inferred title field
    slug: "{{slug}}" # 文件名字模版，{{slug}} 取自title
    fields: # 定义front matter的显示与数据类型
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Authors",
          name: "authors",
          widget: "string",
          default: "Hsiang_Nianian",
        }
      - { label: "Type", name: "type", widget: "string", default: "post" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Series", name: "series", widget: "list", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Lastmod",
          name: "lastmod",
          widget: "date",
          default: "",
          required: false,
          format: "YYYY-MM-DD",
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - {
          label: "Featured Image",
          name: "featured",
          widget: "image",
          required: false,
        }
      - {
          label: "Featured Alt",
          name: "featuredalt",
          widget: "string",
          required: false,
        }
      - {
          label: "Featured Path",
          name: "featuredpath",
          widget: "string",
          default: "img/post",
          required: false,
        }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: false,
          required: false,
        }
      - {
          label: "Show TOC",
          name: "showtoc",
          widget: "boolean",
          default: true,
          required: false,
        }
      - { label: "Post Content", name: "body", widget: "markdown" }
