from __future__ import annotations

class CoreMessage:
    def __init__(self) -> None: ...
    @staticmethod
    def from_plain_text(text: str) -> CoreMessage: ...
    @staticmethod
    def from_json(payload: str) -> CoreMessage: ...
    @staticmethod
    def from_onebot11_json(payload: str) -> CoreMessage: ...
    def push_text(self, text: str) -> None: ...
    def push(self, kind: str, data_json: str | None = None) -> None: ...
    def extend_from_json(self, payload: str) -> None: ...
    def plain_text(self) -> str: ...
    def render_text(self) -> str: ...
    def to_json(self) -> str: ...
    def to_onebot11_json(self) -> str: ...
    def copy(self) -> CoreMessage: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def next_event_id() -> str: ...
def deep_merge_json(base_json: str, overlay_json: str) -> str: ...
def normalize_onebot11_event(
    raw_json: str,
    adapter_name: str = "onebot11",
    platform: str = "qq",
) -> str: ...
