"""Thin Python wrappers around the Rust core extension."""

from __future__ import annotations

import json
from collections.abc import Mapping
from typing import Any, cast

from ._core import CoreMessage, deep_merge_json, next_event_id, normalize_onebot11_event


def merge_dicts(base: Mapping[str, Any], overlay: Mapping[str, Any]) -> dict[str, Any]:
    """Return a deep merge of two JSON-compatible dictionaries."""
    return cast(
        dict[str, Any],
        json.loads(deep_merge_json(json.dumps(base), json.dumps(overlay))),
    )


def new_event_id() -> str:
    """Return a globally unique event identifier generated by the Rust core."""
    return next_event_id()


def normalize_onebot11_payload(
    raw: Mapping[str, Any], *, adapter_name: str = "onebot11", platform: str = "qq"
) -> dict[str, Any]:
    """Normalize a raw OneBot11 event into iamai's event dictionary shape."""
    return cast(
        dict[str, Any],
        json.loads(normalize_onebot11_event(json.dumps(raw), adapter_name, platform)),
    )


__all__ = ["CoreMessage", "merge_dicts", "new_event_id", "normalize_onebot11_payload"]
