[project]
name = "iamai-adapter-red"
version = "3.3.0"
description = "Red adapter for iamai."
authors = [{ name = "简律纯", email = "i@jyunko.cn" }]
license = { text = "MIT" }
readme = "README.md"
keywords = ["bot", "chatbot", "red"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
    "Framework :: Robot Framework",
    "Framework :: Robot Framework :: Library",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Communications :: Chat",
]
requires-python = ">=3.8"
dependencies = ["iamai>=3.3"]

[project.urls]
Homepage = "https://iamai.retrofor.space/"
Documentation = "https://iamai.retrofor.space/"
Repository = "https://github.com/retrofor/iamai"
Changelog = "https://iamai.retrofor.space/changelog.html"

[tool.hatch.build]
exclude = ["iamai/__init__.py", "iamai/adapter/__init__.py"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"