[tool.poetry]
name = "iamai-adapter-mirai"
version = "3.2.3"
description = "Mirai adapter for iamai."
authors = ["简律纯 <i@jyunko.cn>"]
license = "GPL-3.0 License"
readme = "README.md"
homepage = "https://retrofor.space/"
repository = "https://github.com/retrofor/iamai"
documentation = "https://iamai.retrofor.space/"
keywords = ["bot", "chatbot", "qq", "qqbot", "mirai"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
    "Framework :: Robot Framework",
    "Framework :: Robot Framework :: Library",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Communications :: Chat",
]
packages = [{ include = "iamai" }]
exclude = ["iamai/__init__.py", "iamai/adapter/__init__.py"]

[tool.poetry.dependencies]
python = "^3.8"
iamai = ">=3.2"

[tool.poetry.dev-dependencies]
iamai = { path = "../../", develop = true }

[tool.pydantic-pycharm-plugin]
ignore-init-method-arguments = true

[tool.black]
target-version = ["py38", "py39", "py310"]

[tool.isort]
profile = "black"
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
src_paths = ["iamai", "tests"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
