name: Release-Packages

on:
  push:
    tags:
      - "v*"
    paths:
      - "packages/*"
  # release:
  #   types: [published]
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: ./.github/actions/setup-python

      - name: Build Packages
        run: |
          uv build --package iamai-adapter-cqhttp
          uv build --package iamai-adapter-apscheduler
          uv build --package iamai-adapter-bililive
          uv build --package iamai-adapter-console
          uv build --package iamai-adapter-dingtalk
          uv build --package iamai-adapter-gensokyo
          uv build --package iamai-adapter-kook
          uv build --package iamai-adapter-red

      - name: Publish Packages
        run: uv publish