name: Translation Helper

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Check if trans label exists
        id: check_label
        uses: actions/github-script@v4
        with:
          script: |
            const issueLabels = context.payload.issue.labels.map(label => label.name);
            const hasTransLabel = issueLabels.includes('trans');
            core.setOutput('hasTransLabel', hasTransLabel)
      
      - name: Run translation helper
        if: steps.check_label.outputs.hasTransLabel == 'true'
        uses: actions-cool/translation-helper@v1.2.0
